### ISSUE TITLE
Rename repo to sourcegraph-sentry

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph-sentry#28]
- For consistency with other extensions: https://sourcegraph.com/search?q=repo%3A%2Fsourcegraph%2Fsourcegraph-
- Because if people in other GitHub orgs make Sourcegraph extensions (or fork ours), they would want to follow a naming pattern of `sourcegraph-whatever` not just `whatever`, so we should pick one consistent way for the whole community

The extension itself should still be named `sourcegraph/sentry` not `sourcegraph/sourcegraph-sentry`.

**Comment by vanesa** [comment]
Ok, done.
