### ISSUE TITLE
Readme should give necessary set up instructions

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph-sentry#3]
The extension's README should give clear, reproducible, up-to-date instructions on how to set up the extension:

- [ ] Explain what the extension does by default, with no configuration added
- [ ] Explain what the extension can do once configured
- [ ] Explain how to customize it to your needs using settings
- [ ] Explain that these settings can be set at org-level through organization settings (link to the relevant Sourcegraph docs)

**Comment by vanesa** [comment]
Resolved with this PR: https://github.com/sourcegraph/sourcegraph-sentry/pull/45
