### ISSUE TITLE
Sentry extension should wrap the query in double quotes

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph-sentry#40]
With the following config:

```
  "sentry.projects": [
    {
      "name": "Browser extension",
      "projectId": "%PROJECT%",
      "filters": [{
        "repositories": [
          "sourcegraph/sourcegraph"
        ],
        "files": [
          "(browser|shared).*\\.tsx?"
        ]
      }]
    }
  ]
```

The hover on `throw new Error('(adjustPosition) could not find code element for line provided')` links to:

https://sentry.io/organizations/sourcegraph/issues/?project=1334031&query=is%3Aunresolved+%28adjustPosition%29+could+not+find+code+element+for+line+provided&statsPeriod=14d

This does not work on Sentry:

![image](https://user-images.githubusercontent.com/1741180/58206064-d5792080-7c94-11e9-8adc-08c053a48f72.png)

The following would work on Sentry (with the query wrapped in quotes): https://sentry.io/organizations/sourcegraph/issues/?project=1334031&query=is%3Aunresolved+%22%28adjustPosition%29+could+not+find+code+element+for+line+provided%22&statsPeriod=14d

![image](https://user-images.githubusercontent.com/1741180/58206120-f8a3d000-7c94-11e9-9efa-b51f6b84d478.png)

**Comment by vanesa** [comment]
Resolved with https://github.com/sourcegraph/sourcegraph-sentry/pull/44
