### ISSUE TITLE
Unclear why I should specify line matches

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph-sentry#42]
Based on the docs, it's unclear to me why I should specify line matches, if my language is already supported.

- What exactly is included in the language support?
- Do I _have_ to specify the line match patterns or are they optional? Can I have examples of cases where they might be useful to me?

**Comment by vanesa** [comment]
Resolved with https://github.com/sourcegraph/sourcegraph-sentry/pull/45.
